# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmEncriptar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from encriptacion import *
from PyQt5.QtWidgets import QFileDialog
import cv2
import numpy as np
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMessageBox




class Ui_frmEncriptar(object):
    def setupUi(self, frmEncriptar):
        frmEncriptar.setObjectName("frmEncriptar")
        frmEncriptar.resize(682, 477)
        self.centralwidget = QtWidgets.QWidget(frmEncriptar)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.encriptartexto = QtWidgets.QWidget()
        self.encriptartexto.setObjectName("encriptartexto")
        self.guardar = QtWidgets.QPushButton(self.encriptartexto)
        self.guardar.setGeometry(QtCore.QRect(510, 200, 101, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/disco-flexible.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guardar.setIcon(icon)
        self.guardar.setObjectName("guardar")
        self.cargar = QtWidgets.QPushButton(self.encriptartexto)
        self.cargar.setGeometry(QtCore.QRect(510, 160, 101, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/subir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cargar.setIcon(icon1)
        self.cargar.setObjectName("cargar")
        self.label_2 = QtWidgets.QLabel(self.encriptartexto)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.encriptar = QtWidgets.QPushButton(self.encriptartexto)
        self.encriptar.setGeometry(QtCore.QRect(510, 40, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Downloads/proteger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.encriptar.setIcon(icon2)
        self.encriptar.setObjectName("encriptar")
        self.desencriptar = QtWidgets.QPushButton(self.encriptartexto)
        self.desencriptar.setGeometry(QtCore.QRect(510, 80, 101, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Downloads/encriptado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.desencriptar.setIcon(icon3)
        self.desencriptar.setObjectName("desencriptar")
        self.textoencriptado = QtWidgets.QLabel(self.encriptartexto)
        self.textoencriptado.setGeometry(QtCore.QRect(80, 280, 411, 111))
        self.textoencriptado.setText("")
        self.textoencriptado.setObjectName("textoencriptado")
        self.limpiar = QtWidgets.QPushButton(self.encriptartexto)
        self.limpiar.setGeometry(QtCore.QRect(510, 120, 101, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Downloads/barriendo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.limpiar.setIcon(icon4)
        self.limpiar.setObjectName("limpiar")
        self.label = QtWidgets.QLabel(self.encriptartexto)
        self.label.setGeometry(QtCore.QRect(70, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.contenido = QtWidgets.QTextEdit(self.encriptartexto)
        self.contenido.setGeometry(QtCore.QRect(70, 40, 421, 191))
        self.contenido.setObjectName("contenido")
        self.tabWidget.addTab(self.encriptartexto, "")
        self.encriptarimagen = QtWidgets.QWidget()
        self.encriptarimagen.setObjectName("encriptarimagen")
        self.label_3 = QtWidgets.QLabel(self.encriptarimagen)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.encriptar_2 = QtWidgets.QPushButton(self.encriptarimagen)
        self.encriptar_2.setGeometry(QtCore.QRect(420, 100, 101, 31))
        self.encriptar_2.setIcon(icon2)
        self.encriptar_2.setObjectName("encriptar_2")
        self.desencriptar_2 = QtWidgets.QPushButton(self.encriptarimagen)
        self.desencriptar_2.setGeometry(QtCore.QRect(420, 140, 101, 31))
        self.desencriptar_2.setIcon(icon3)
        self.desencriptar_2.setObjectName("desencriptar_2")
        self.limpiar_2 = QtWidgets.QPushButton(self.encriptarimagen)
        self.limpiar_2.setGeometry(QtCore.QRect(420, 180, 101, 31))
        self.limpiar_2.setIcon(icon4)
        self.limpiar_2.setObjectName("limpiar_2")
        self.cargar_2 = QtWidgets.QPushButton(self.encriptarimagen)
        self.cargar_2.setGeometry(QtCore.QRect(420, 220, 101, 31))
        self.cargar_2.setIcon(icon1)
        self.cargar_2.setObjectName("cargar_2")
        self.imagenencriptada = QtWidgets.QLabel(self.encriptarimagen)
        self.imagenencriptada.setGeometry(QtCore.QRect(30, 90, 361, 231))
        self.imagenencriptada.setText("")
        self.imagenencriptada.setObjectName("imagenencriptada")
        self.tabWidget.addTab(self.encriptarimagen, "")
        frmEncriptar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmEncriptar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName("menubar")
        frmEncriptar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmEncriptar)
        self.statusbar.setObjectName("statusbar")
        frmEncriptar.setStatusBar(self.statusbar)

        self.retranslateUi(frmEncriptar)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmEncriptar)

        # Llamado a funciones para texto (ya existentes)
        self.encriptar.clicked.connect(self.encriptar_texto)
        self.limpiar.clicked.connect(self.limpiar_texto)
        self.desencriptar.clicked.connect(self.desencriptar_texto)
        self.cargar.clicked.connect(self.cargar_archivo)
        self.guardar.clicked.connect(self.guardar_archivo)

        # Llamado a funciones para imagen
        self.cargar_2.clicked.connect(self.cargar_imagen)  # Para cargar imagen
        self.encriptar_2.clicked.connect(self.encriptar_imagen)  # Para encriptar imagen
        self.desencriptar_2.clicked.connect(self.desencriptar_imagen)  # Para desencriptar imagen
        self.limpiar_2.clicked.connect(self.limpiar_imagen)  # Para limpiar la vista de la imagen


    def retranslateUi(self, frmEncriptar):
        _translate = QtCore.QCoreApplication.translate
        frmEncriptar.setWindowTitle(_translate("frmEncriptar", "MainWindow"))
        self.guardar.setText(_translate("frmEncriptar", "Guardar Archivo"))
        self.cargar.setText(_translate("frmEncriptar", "Cargar archivo"))
        self.label_2.setText(_translate("frmEncriptar", "Mensaje Encriptado"))
        self.encriptar.setText(_translate("frmEncriptar", "Encriptar"))
        self.desencriptar.setText(_translate("frmEncriptar", "desencriptar"))
        self.limpiar.setText(_translate("frmEncriptar", "Limpiar"))
        self.label.setText(_translate("frmEncriptar", "Mensaje"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encriptartexto), _translate("frmEncriptar", "encriptar texto"))
        self.label_3.setText(_translate("frmEncriptar", "Imagen:"))
        self.encriptar_2.setText(_translate("frmEncriptar", "Encriptar"))
        self.desencriptar_2.setText(_translate("frmEncriptar", "desencriptar"))
        self.limpiar_2.setText(_translate("frmEncriptar", "Limpiar"))
        self.cargar_2.setText(_translate("frmEncriptar", "Cargar archivo"))
        # self.guardar_2.setText(_translate("frmEncriptar", "Guardar Archivo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encriptarimagen), _translate("frmEncriptar", "encriptar imagen"))
    
    def encriptar_texto(self):
        texto_original = self.contenido.toPlainText()
        if texto_original.strip():  
            texto_encriptado = encriptar_texto(texto_original)
            self.textoencriptado.setText(f"{texto_encriptado}")
            print("Texto encriptado: ", texto_encriptado)
            self.contenido.setText("")  
        else:
            self.textoencriptado.setText("No hay texto para encriptar.")

    def desencriptar_texto(self):
        texto_encriptado = self.contenido.toPlainText()
        if texto_encriptado.strip():  
            try:
                texto_original = desencriptar_texto(texto_encriptado)
                self.textoencriptado.setText(f"{texto_original}")
                print("Texto desencriptado: ", texto_original)
            except Exception as e:
                self.textoencriptado.setText("No hay texto para desencriptar.")
        else:
            self.textoencriptado.setText("No hay texto para desencriptar.")

    def limpiar_texto(self):
        self.contenido.clear()
        self.textoencriptado.clear()

    def cargar_archivo(self):

        archivo, _ = QFileDialog.getOpenFileName(None, "Abrir archivo", "", "Archivos de texto (*.txt)")
        if archivo:
            with open(archivo, 'r', encoding='utf-8') as f: 
                contenido = f.read()
                self.contenido.setText(contenido)

    def guardar_archivo(self):
        archivo, _ = QFileDialog.getSaveFileName(None, "Guardar archivo", "", "Archivos de texto (*.txt)")
        if archivo:
            texto_a_guardar = self.textoencriptado.text().strip()
            with open(archivo, 'w', encoding='utf-8') as f:
                    f.write(texto_a_guardar)
           

    def cargar_imagen(self):
        pass
    
    def encriptar_imagen(self):
        pass
        
    def desencriptar_imagen(self):
        pass
            
    def limpiar_imagen(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmEncriptar = QtWidgets.QMainWindow()
    ui = Ui_frmEncriptar()
    ui.setupUi(frmEncriptar)
    frmEncriptar.show()
    sys.exit(app.exec_())

    