# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 438)
        MainWindow.setMinimumSize(QtCore.QSize(827, 438))
        MainWindow.setMaximumSize(QtCore.QSize(827, 438))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUsuario = QtWidgets.QLabel(self.centralwidget)
        self.lblUsuario.setEnabled(True)
        self.lblUsuario.setGeometry(QtCore.QRect(410, 110, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setObjectName("lblUsuario")
        self.lblContrasena = QtWidgets.QLabel(self.centralwidget)
        self.lblContrasena.setGeometry(QtCore.QRect(410, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblContrasena.setFont(font)
        self.lblContrasena.setObjectName("lblContrasena")
        self.txtUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUsuario.setGeometry(QtCore.QRect(520, 130, 113, 20))
        self.txtUsuario.setObjectName("txtUsuario")
        self.txtContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContrasena.setGeometry(QtCore.QRect(520, 170, 113, 20))
        self.txtContrasena.setObjectName("txtContrasena")
        self.Aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.Aceptar.setGeometry(QtCore.QRect(560, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Aceptar.setFont(font)
        self.Aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Aceptar.setIcon(icon)
        self.Aceptar.setObjectName("Aceptar")
        self.cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.cancelar.setGeometry(QtCore.QRect(380, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelar.setFont(font)
        self.cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelar.setIcon(icon1)
        self.cancelar.setObjectName("cancelar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 90, 201, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("proteger.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 340, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblUsuario.setText(_translate("MainWindow", "Usuario:"))
        self.lblContrasena.setText(_translate("MainWindow", "Contrasena:"))
        self.Aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.label_2.setText(_translate("MainWindow", "Realizado por Kalid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
