# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Windowbuttom.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Windowbuttom(object):
    def setupUi(self, Windowbuttom):
        Windowbuttom.setObjectName("Windowbuttom")
        Windowbuttom.resize(665, 421)
        self.centralwidget = QtWidgets.QWidget(Windowbuttom)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 150, 151, 61))
        self.pushButton.setObjectName(" ")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 110, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Windowbuttom.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Windowbuttom)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        self.menubar.setObjectName("menubar")
        Windowbuttom.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Windowbuttom)
        self.statusbar.setObjectName("statusbar")
        Windowbuttom.setStatusBar(self.statusbar)

        self.retranslateUi(Windowbuttom)
        QtCore.QMetaObject.connectSlotsByName(Windowbuttom)

    def retranslateUi(self, Windowbuttom):
        _translate = QtCore.QCoreApplication.translate
        Windowbuttom.setWindowTitle(_translate("Windowbuttom", "MainWindow"))
        self.pushButton.setText(_translate("Windowbuttom", "Desencriptar"))
        self.label.setText(_translate("Windowbuttom", "               Acceder -->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Windowbuttom = QtWidgets.QMainWindow()
    ui = Ui_Windowbuttom()
    ui.setupUi(Windowbuttom)
    Windowbuttom.show()
    sys.exit(app.exec_())
